[www]
user = www-data
group = www-data
listen = 9000
listen.owner = www-data
listen.group = www-data
pm = dynamic
pm.max_children = 100
pm.start_servers = 20
pm.min_spare_servers = 10
pm.max_spare_servers = 50
pm.max_requests = 1000
pm.process_idle_timeout = 10s
request_terminate_timeout = 1800
slowlog = /var/log/php-fpm/slow.log
request_slowlog_timeout = 30
php_admin_value[upload_max_filesize] = "100M"
php_admin_value[post_max_size] = "100M"
php_admin_value[memory_limit] = "1024M"
php_admin_value[max_execution_time] = "1800"
php_admin_value[max_input_time] = "1800"
php_admin_value[date.timezone] = "Europe/Moscow"
php_admin_value[opcache.memory_consumption] = "256"
php_admin_value[opcache.interned_strings_buffer] = "16"
php_admin_value[opcache.max_accelerated_files] = "10000"
php_admin_value[opcache.revalidate_freq] = "0"
php_admin_value[opcache.fast_shutdown] = "1" 